# load the uncleaned data and perform cleaning/transformation operations

## export the cleaned data

In [1]:
import pandas as pd
import re

## Customer

In [2]:
c_df=pd.read_csv('customer.csv')

In [3]:
c_df.head(n=5)

,customer_id,age_in_months,gender,occupation,married,registered_date,premium_status
0,C754,255.67,F,Student,y,22-Apr-23,not opted
1,C854,251.25,F,Teacher,y,10-Mar-19,no
2,C132,214.90,male,Doctor,y,08-Jul-19,not opted
3,C833,524.94,female,Farmer,y,09-Oct-20,yes
4,C928,634.65,fem,Unemployed,y,24-Dec-17,no

# data cleaning

1. check for duplicates and handle them
2. check for missing values and handle them
3. check for invalid data types and handle them
4. Drop the unwanted column

In [4]:
c_df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
895    False
896    False
897    False
898    False
899    False
Length: 900, dtype: bool

In [5]:
c_df.duplicated().any()

np.False_

In [6]:
c_df.duplicated(subset='customer_id').any() #to check pk is duplicated

np.True_

In [7]:
c_df.drop_duplicates(subset='customer_id')#subset means col name

,customer_id,age_in_months,gender,occupation,married,registered_date,premium_status
0,C754,255.67,F,Student,y,22-Apr-23,not opted
1,C854,251.25,F,Teacher,y,10-Mar-19,no
2,C132,214.90,male,Doctor,y,08-Jul-19,not opted
3,C833,524.94,female,Farmer,y,09-Oct-20,yes
4,C928,634.65,fem,Unemployed,y,24-Dec-17,no
...,...,...,...,...,...,...,...
887,C686,276.37,M,Teacher,n,09-Oct-20,not opted
889,C805,552.57,female,Doctor,n,07-Mar-24,not opted
890,C425,233.91,female,Business,y,29-Sep-23,yes
892,C410,421.50,fem,Business,n,08-Feb-24,not opted
896,C603,436.92,male,Doctor,y,12-Jun-25,no

In [8]:
c_df.shape

(900, 7)

In [9]:
c_df=c_df.drop_duplicates(subset='customer_id')

In [10]:
c_df.shape

(569, 7)

In [11]:
c_df.info()#to find missing values

<class 'pandas.DataFrame'>
Index: 569 entries, 0 to 896
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   customer_id      569 non-null    str
 1   age_in_months    567 non-null    float64
 2   gender           569 non-null    str
 3   occupation       569 non-null    str
 4   married          569 non-null    str
 5   registered_date  569 non-null    str
 6   premium_status   569 non-null    str
dtypes: float64(1), str(6)
memory usage: 35.6 KB

In [12]:
# age_in_months need to be clean
age_mean=c_df['age_in_months'].mean()
age_mean

np.float64(448.21777777777777)

In [13]:
c_df['age_in_months']=c_df['age_in_months'].fillna(age_mean)

In [14]:
c_df.tail() #it give row values

,customer_id,age_in_months,gender,occupation,married,registered_date,premium_status
887,C686,276.37,M,Teacher,n,09-Oct-20,not opted
889,C805,552.57,female,Doctor,n,07-Mar-24,not opted
890,C425,233.91,female,Business,y,29-Sep-23,yes
892,C410,421.50,fem,Business,n,08-Feb-24,not opted
896,C603,436.92,male,Doctor,y,12-Jun-25,no

In [15]:
# dataframe name[series name]

In [16]:

# converting string based date to actual data -->pd.to_datetime
# always pass series
pd.to_datetime(c_df['registered_date'])

C:\Users\ANJANA\AppData\Local\Temp\ipykernel_1988\2624072549.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(c_df['registered_date'])

0     2023-04-22
1     2019-03-10
2     2019-07-08
3     2020-10-09
4     2017-12-24
         ...
887   2020-10-09
889   2024-03-07
890   2023-09-29
892   2024-02-08
896   2025-06-12
Name: registered_date, Length: 569, dtype: datetime64[us]

In [17]:
c_df['registered_date']=pd.to_datetime(c_df['registered_date'])

C:\Users\ANJANA\AppData\Local\Temp\ipykernel_1988\3053993440.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  c_df['registered_date']=pd.to_datetime(c_df['registered_date'])

In [18]:
c_df.tail()

,customer_id,age_in_months,gender,occupation,married,registered_date,premium_status
887,C686,276.37,M,Teacher,n,2020-10-09,not opted
889,C805,552.57,female,Doctor,n,2024-03-07,not opted
890,C425,233.91,female,Business,y,2023-09-29,yes
892,C410,421.50,fem,Business,n,2024-02-08,not opted
896,C603,436.92,male,Doctor,y,2025-06-12,no

In [19]:
c_df.info()

<class 'pandas.DataFrame'>
Index: 569 entries, 0 to 896
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   customer_id      569 non-null    str
 1   age_in_months    569 non-null    float64
 2   gender           569 non-null    str
 3   occupation       569 non-null    str
 4   married          569 non-null    str
 5   registered_date  569 non-null    datetime64[us]
 6   premium_status   569 non-null    str
dtypes: datetime64[us](1), float64(1), str(5)
memory usage: 35.6 KB

# Feature Engineering(Data Transformation)

In [20]:
# unique shows unique values in the format of list
c_df['customer_id'].unique()

<StringArray>
['C754', 'C854', 'C132', 'C833', 'C928', 'C448', 'C489', 'C649', 'C691',
 'C975',
 ...
 'C314', 'C985', 'C642', 'C931', 'C633', 'C686', 'C805', 'C425', 'C410',
 'C603']
Length: 569, dtype: str

In [21]:
c_df['gender'].unique()

<StringArray>
['F', 'male', 'female', 'fem', 'Female', 'Male', 'M']
Length: 7, dtype: str

In [22]:
c_df['gender'].replace({'F':'Female','male':'Male','female':'Female','fem':'Female','M':'Male'})

0      Female
1      Female
2        Male
3      Female
4      Female
        ...
887      Male
889    Female
890    Female
892    Female
896      Male
Name: gender, Length: 569, dtype: str

In [23]:
c_df['gender']=c_df['gender'].replace({'F':'Female','male':'Male','female':'Female','fem':'Female','M':'Male'})

In [24]:
c_df['married']=c_df['married'].replace({'y':1, 'n':0})

In [25]:
c_df['premium_status']=c_df['premium_status'].replace({'yes':1,'opted':1,'no':0,"not opted":0})

In [26]:
c_df['age_in_months']=(c_df['age_in_months']//12).astype(int)

In [27]:
c_df.tail(1)

,customer_id,age_in_months,gender,occupation,married,registered_date,premium_status
896,C603,36,Male,Doctor,1,2025-06-12,0

In [28]:
# the o/p is in table format give table name
# if o/p is in series format give series name to store
c_df=c_df.rename(columns={'age_in_months':'age'})

In [29]:
c_df.tail(n=3)

    customer_id  age  gender occupation married registered_date premium_status
890        C425   19  Female   Business       1      2023-09-29              1
892        C410   35  Female   Business       0      2024-02-08              0
896        C603   36    Male     Doctor       1      2025-06-12              0

In [30]:
c_df.reset_index()

,index,customer_id,age,gender,occupation,married,registered_date,premium_status
0,0,C754,21,Female,Student,1,2023-04-22,0
1,1,C854,20,Female,Teacher,1,2019-03-10,0
2,2,C132,17,Male,Doctor,1,2019-07-08,0
3,3,C833,43,Female,Farmer,1,2020-10-09,1
4,4,C928,52,Female,Unemployed,1,2017-12-24,0
...,...,...,...,...,...,...,...,...
564,887,C686,23,Male,Teacher,0,2020-10-09,0
565,889,C805,46,Female,Doctor,0,2024-03-07,0
566,890,C425,19,Female,Business,1,2023-09-29,1
567,892,C410,35,Female,Business,0,2024-02-08,0
568,896,C603,36,Male,Doctor,1,2025-06-12,0

In [31]:
# deleting old index
c_df=c_df.reset_index(drop=True)

In [32]:
c_df[['age','premium_status']]

     age premium_status
0     21              0
1     20              0
2     17              0
3     43              1
4     52              0
..   ...            ...
564   23              0
565   46              0
566   19              1
567   35              0
568   36              0

[569 rows x 2 columns]

In [33]:
c_df['age'].agg(['min','max'])

min    16
max    58
Name: age, dtype: int64

In [34]:
def age_categ(age):
    if age>=14 and age<18:
        return 'Children'
    elif age>=18 and age<=25:
        return 'Teenage'
    elif age>25 and age<60:
        return 'Adult'
    elif age>=60 and age<=100:
        return 'Senior'
    else:
        return None

In [35]:
c_df['age_category']=c_df['age'].apply(age_categ)
# apply methods calls the age_categ for every cell value
# =>569 times(total_cells=569)

In [36]:
c_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   customer_id      569 non-null    str
 1   age              569 non-null    int64
 2   gender           569 non-null    str
 3   occupation       569 non-null    str
 4   married          569 non-null    object
 5   registered_date  569 non-null    datetime64[us]
 6   premium_status   569 non-null    object
 7   age_category     569 non-null    str
dtypes: datetime64[us](1), int64(1), object(2), str(4)
memory usage: 35.7+ KB

## Product

In [37]:
p_df=pd.read_csv('product.csv')

In [38]:
p_df.shape

(110, 10)

In [39]:
p_df.columns

Index(['product_id', 'product_name_category', 'price', 'discount',
       'expiry_date', 'stock', 'ratings', 'discounted amount', 'amazon',
       'flipkart'],
      dtype='str')

In [40]:
p_df.head()

,product_id,product_name_category,price,discount,expiry_date,stock,ratings,discounted amount,amazon,flipkart
0,P1000,Shoes-Footwear,NaN,not applicable,12-Jan-26,available,two,NaN,0,1
1,P1001,Soap-Hygiene,100rs,10% off,12-Jan-26,not available,5*,NaN,1,0
2,P1002,Chair-Furniture,1200rs,not applicable,not applicable,not available,two,NaN,1,1
3,P1003,Watch--Accessories,15$,flat 1000,04-Dec-27,available,two,NaN,1,0
4,P1004,TV--Electronics,999rs+12%gst,not applicable,12-Jan-26,available,two,NaN,0,1

In [41]:
p_df.duplicated().any()

np.True_

In [42]:
p_df.drop_duplicates(inplace=True) #inplace is used to store permanent changes or assign method

In [43]:
p_df.duplicated(subset='product_id').any()

np.True_

In [44]:
p_df.drop_duplicates(subset='product_id',inplace=True)

In [45]:
p_df.info()

<class 'pandas.DataFrame'>
Index: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   product_id             100 non-null    str
 1   product_name_category  100 non-null    str
 2   price                  99 non-null     str
 3   discount               100 non-null    str
 4   expiry_date            100 non-null    str
 5   stock                  100 non-null    str
 6   ratings                100 non-null    str
 7   discounted amount      0 non-null      float64
 8   amazon                 100 non-null    int64
 9   flipkart               100 non-null    int64
dtypes: float64(1), int64(2), str(7)
memory usage: 8.6 KB

In [46]:
p_df['price'].isnull().sum() #1 missing value

np.int64(1)

In [47]:
p_df['discounted amount'].isnull().sum() #100 missing value

np.int64(100)

In [48]:
p_df.dropna(subset='price',axis=0,inplace=True)

In [49]:
p_df['expiry_date']=pd.to_datetime(p_df['expiry_date'],errors='coerce')

C:\Users\ANJANA\AppData\Local\Temp\ipykernel_1988\3679721228.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  p_df['expiry_date']=pd.to_datetime(p_df['expiry_date'],errors='coerce')

In [50]:
p_df.info()

<class 'pandas.DataFrame'>
Index: 99 entries, 1 to 99
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   product_id             99 non-null     str
 1   product_name_category  99 non-null     str
 2   price                  99 non-null     str
 3   discount               99 non-null     str
 4   expiry_date            68 non-null     datetime64[us]
 5   stock                  99 non-null     str
 6   ratings                99 non-null     str
 7   discounted amount      0 non-null      float64
 8   amazon                 99 non-null     int64
 9   flipkart               99 non-null     int64
dtypes: datetime64[us](1), float64(1), int64(2), str(6)
memory usage: 8.5 KB

In [51]:
p_df['product_name_category']=p_df['product_name_category'].str.replace('--','-') #  column_name.str.(any string method)  it work cell by cell

In [52]:
p_df[['product','category']]=  p_df['product_name_category'].str.split('-',expand=True)  #expand split and do the 2 columns

In [53]:
p_df.head()

,product_id,product_name_category,price,discount,expiry_date,stock,ratings,discounted amount,amazon,flipkart,product,category
1,P1001,Soap-Hygiene,100rs,10% off,2026-01-12,not available,5*,NaN,1,0,Soap,Hygiene
2,P1002,Chair-Furniture,1200rs,not applicable,NaT,not available,two,NaN,1,1,Chair,Furniture
3,P1003,Watch-Accessories,15$,flat 1000,2027-12-04,available,two,NaN,1,0,Watch,Accessories
4,P1004,TV-Electronics,999rs+12%gst,not applicable,2026-01-12,available,two,NaN,0,1,TV,Electronics
5,P1005,Soap-Hygiene,100rs,not applicable,NaT,available,two,NaN,1,1,Soap,Hygiene

In [54]:
p_df=p_df.drop(columns=['product_name_category'])

In [55]:
p_df.head()

,product_id,price,discount,expiry_date,stock,ratings,discounted amount,amazon,flipkart,product,category
1,P1001,100rs,10% off,2026-01-12,not available,5*,NaN,1,0,Soap,Hygiene
2,P1002,1200rs,not applicable,NaT,not available,two,NaN,1,1,Chair,Furniture
3,P1003,15$,flat 1000,2027-12-04,available,two,NaN,1,0,Watch,Accessories
4,P1004,999rs+12%gst,not applicable,2026-01-12,available,two,NaN,0,1,TV,Electronics
5,P1005,100rs,not applicable,NaT,available,two,NaN,1,1,Soap,Hygiene

In [56]:
p_df['price']=p_df['price'].str.replace('rs','')
# # rs will be removed in each and every cell value
p_df['price']

1            100
2           1200
3            15$
4     999+12%gst
5            100
         ...
95           100
96          1200
97     500+5%gst
98          1200
99     500+5%gst
Name: price, Length: 99, dtype: str

In [57]:
p_df['price'].unique()

<StringArray>
['100', '1200', '15$', '999+12%gst', '500+5%gst']
Length: 5, dtype: str

In [58]:
# 15$==>15*90  doller to rupee
15*90

1350

In [59]:
999*12/100 #12% is the gst

119.88

In [60]:
999+119.88  #999+(999*12/100)

1118.88

In [61]:
# def price_clean(p):
#     if '+' in p:
#         p_lst=p.split('+')
#         v1=float(p_lst[0])
#         v2=float(p_lst[1].replace('%gst',''))
#         return v1+(v2/100*v1)
#     elif '$' in p:
#         v1=float(p.replace('$',''))*90
#         return v1
#     else:
#         return float(p)

# p_df['price']=p_df['price'].apply(price_clean).astype('int')
# apply methd pass the price value to prie_clean()-(cell by cell or row by row)

In [62]:

p_df['price']

1            100
2           1200
3            15$
4     999+12%gst
5            100
         ...
95           100
96          1200
97     500+5%gst
98          1200
99     500+5%gst
Name: price, Length: 99, dtype: str

In [63]:
import re

In [64]:
def price_clean(p):
    if '+' in p:
        v1=float(re.findall('\\d+',p)[0])
        v2=float(re.findall('\\d+',p)[1])
        return v1+(v2/100*v1)
    elif  '$' in p:
        v1=float(re.findall('(\\d+)\\$',p)[0])
        return v1*90
    else:
        return float(p)

In [65]:
p_df['price']=p_df['price'].apply(price_clean).astype(int)

In [66]:
p_df['price']

1      100
2     1200
3     1350
4     1118
5      100
      ...
95     100
96    1200
97     525
98    1200
99     525
Name: price, Length: 99, dtype: int64

In [67]:
p_df['discount'].unique()

<StringArray>
['10% off', 'not applicable', 'flat 1000', 'upto 30%', 'flat700']
Length: 5, dtype: str

In [68]:
def disc_amt(r):
    d=r['discount'] #single cell value of the particular row
    p=r['price']
    if 'off' in d:
        n=float(re.findall('(\\d+)%\\s?off',d)[0])
        return p-(p*n/100) #assume 1000-(1000*20/100)
    elif 'flat' in d:
        n=float(re.findall('flat\\s?(\\d+)',d)[0])
        return (p-n)  #assume 1000 price -flat 300 =700
    elif 'upto' in d:
        n=float(re.findall('upto\\s?(\\d+)%',d)[0])//2 #upto 30% take half means 15?
        return p-(p*n/100)
    else:
        return float(p)


        
p_df['discounted amount']=p_df[['discount','price']].apply(disc_amt,axis=1) #axis=1 data will pass row by row

In [69]:
p_df

,product_id,price,discount,expiry_date,stock,ratings,discounted amount,amazon,flipkart,product,category
1,P1001,100,10% off,2026-01-12,not available,5*,90.0,1,0,Soap,Hygiene
2,P1002,1200,not applicable,NaT,not available,two,1200.0,1,1,Chair,Furniture
3,P1003,1350,flat 1000,2027-12-04,available,two,350.0,1,0,Watch,Accessories
4,P1004,1118,not applicable,2026-01-12,available,two,1118.0,0,1,TV,Electronics
5,P1005,100,not applicable,NaT,available,two,100.0,1,1,Soap,Hygiene
...,...,...,...,...,...,...,...,...,...,...,...
95,P1095,100,not applicable,2026-01-12,available,3 star,100.0,1,1,TV,Electronics
96,P1096,1200,flat 1000,NaT,not available,4 star,200.0,1,0,Shampoo,Hygiene
97,P1097,525,not applicable,2027-12-04,available,4 star,525.0,0,1,Soap,Hygiene
98,P1098,1200,upto 30%,2027-12-04,available,two,1020.0,1,0,Shampoo,Hygiene
99,P1099,525,flat 1000,NaT,not available,5*,-475.0,0,0,Shampoo,Hygiene

In [70]:

# def disc(d):
#     if 'off' in d:
#         n=re.findall('(\\d+)%\\s?off',d)[0]
#         return float(n)
#     elif 'flat' in d:
#         n=re.findall('flat\\s?(\\d+)',d)[0]
#         return float(n)
#     elif 'upto' in d:
#         n=re.findall('upto\\s?(\\d+)%',d)[0]
#         return float(n)
# p_df['discount'].apply(disc).unique()

In [71]:
p_df

,product_id,price,discount,expiry_date,stock,ratings,discounted amount,amazon,flipkart,product,category
1,P1001,100,10% off,2026-01-12,not available,5*,90.0,1,0,Soap,Hygiene
2,P1002,1200,not applicable,NaT,not available,two,1200.0,1,1,Chair,Furniture
3,P1003,1350,flat 1000,2027-12-04,available,two,350.0,1,0,Watch,Accessories
4,P1004,1118,not applicable,2026-01-12,available,two,1118.0,0,1,TV,Electronics
5,P1005,100,not applicable,NaT,available,two,100.0,1,1,Soap,Hygiene
...,...,...,...,...,...,...,...,...,...,...,...
95,P1095,100,not applicable,2026-01-12,available,3 star,100.0,1,1,TV,Electronics
96,P1096,1200,flat 1000,NaT,not available,4 star,200.0,1,0,Shampoo,Hygiene
97,P1097,525,not applicable,2027-12-04,available,4 star,525.0,0,1,Soap,Hygiene
98,P1098,1200,upto 30%,2027-12-04,available,two,1020.0,1,0,Shampoo,Hygiene
99,P1099,525,flat 1000,NaT,not available,5*,-475.0,0,0,Shampoo,Hygiene

In [72]:
p_df['discount']

1            10% off
2     not applicable
3          flat 1000
4     not applicable
5     not applicable
           ...
95    not applicable
96         flat 1000
97    not applicable
98          upto 30%
99         flat 1000
Name: discount, Length: 99, dtype: str

In [73]:
p_df['ratings'].unique()

<StringArray>
['5*', 'two', '4 star', 'three', '3 star']
Length: 5, dtype: str

In [74]:
p_df['ratings']=p_df['ratings'].replace({'5*' : 5, 'two' :2, '4 star':4, 'three':3,'3 star':3})

In [75]:
p_df['ratings'].unique()

array([5, 2, 4, 3], dtype=object)

## orders

In [76]:
o_df=pd.read_csv('orders.csv')

In [77]:
o_df.shape

(502, 8)

In [78]:
o_df.columns

Index(['order_id', 'customer_id', 'product_id', 'order_date', 'net_quantity',
       'payment_mode', 'total_amount', 'amount_saved'],
      dtype='str')

In [79]:
o_df.head()    # assignment total amount merge

,order_id,customer_id,product_id,order_date,net_quantity,payment_mode,total_amount,amount_saved
0,O5000,C415,P1076,06-Jan-25,4.0,credit card,NaN,NaN
1,O5001,C534,P1012,03-Sep-25,5.0,cash,NaN,NaN
2,O5002,C291,P1069,09-Apr-25,4.0,credit card,NaN,NaN
3,O5003,C650,P1090,21-May-23,5.0,cash,NaN,NaN
4,O5004,C856,P1019,05-Jul-23,5.0,debit card,NaN,NaN

In [80]:
o_df.duplicated().any()

np.True_

In [81]:
o_df.drop_duplicates(inplace=True)

In [82]:
pay_mode=o_df['payment_mode'].mode()[0]
o_df['payment_mode']=o_df['payment_mode'].fillna(pay_mode)

In [83]:
o_df.duplicated(subset='order_id').any()

np.False_

In [84]:
o_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      500 non-null    str
 1   customer_id   500 non-null    str
 2   product_id    500 non-null    str
 3   order_date    500 non-null    str
 4   net_quantity  500 non-null    float64
 5   payment_mode  500 non-null    str
 6   total_amount  0 non-null      float64
 7   amount_saved  0 non-null      float64
dtypes: float64(3), str(5)
memory usage: 31.4 KB

In [85]:
o_df['payment_mode'].isnull().sum()

np.int64(0)

In [86]:
o_df.dropna(subset='payment_mode',axis=0,inplace=True)

In [87]:
o_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      500 non-null    str
 1   customer_id   500 non-null    str
 2   product_id    500 non-null    str
 3   order_date    500 non-null    str
 4   net_quantity  500 non-null    float64
 5   payment_mode  500 non-null    str
 6   total_amount  0 non-null      float64
 7   amount_saved  0 non-null      float64
dtypes: float64(3), str(5)
memory usage: 31.4 KB

In [88]:
o_df["order_date"]=pd.to_datetime(o_df["order_date"],errors="coerce")

C:\Users\ANJANA\AppData\Local\Temp\ipykernel_1988\2675400968.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  o_df["order_date"]=pd.to_datetime(o_df["order_date"],errors="coerce")

In [89]:
o_df.head()

,order_id,customer_id,product_id,order_date,net_quantity,payment_mode,total_amount,amount_saved
0,O5000,C415,P1076,2025-01-06,4.0,credit card,NaN,NaN
1,O5001,C534,P1012,2025-09-03,5.0,cash,NaN,NaN
2,O5002,C291,P1069,2025-04-09,4.0,credit card,NaN,NaN
3,O5003,C650,P1090,2023-05-21,5.0,cash,NaN,NaN
4,O5004,C856,P1019,2023-07-05,5.0,debit card,NaN,NaN

In [90]:
o_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      500 non-null    str
 1   customer_id   500 non-null    str
 2   product_id    500 non-null    str
 3   order_date    500 non-null    datetime64[us]
 4   net_quantity  500 non-null    float64
 5   payment_mode  500 non-null    str
 6   total_amount  0 non-null      float64
 7   amount_saved  0 non-null      float64
dtypes: datetime64[us](1), float64(3), str(4)
memory usage: 31.4 KB

In [91]:
o_df["payment_mode"].unique()

<StringArray>
['credit card', 'cash', 'debit card', 'net banking', 'net baNking', 'upi']
Length: 6, dtype: str

In [92]:
{'net baNKing': "net banking"}

{'net baNKing': 'net banking'}

In [93]:
o_df["payment_mode"]=o_df["payment_mode"].replace({'net baNking': 'net banking'})
# o_df["payment_mode"]=o_df["payment_mode"].replace({'net baNking': 'net banking'})

In [94]:
o_df["payment_mode"].unique()

<StringArray>
['credit card', 'cash', 'debit card', 'net banking', 'upi']
Length: 5, dtype: str

In [95]:
o_df.head()

,order_id,customer_id,product_id,order_date,net_quantity,payment_mode,total_amount,amount_saved
0,O5000,C415,P1076,2025-01-06,4.0,credit card,NaN,NaN
1,O5001,C534,P1012,2025-09-03,5.0,cash,NaN,NaN
2,O5002,C291,P1069,2025-04-09,4.0,credit card,NaN,NaN
3,O5003,C650,P1090,2023-05-21,5.0,cash,NaN,NaN
4,O5004,C856,P1019,2023-07-05,5.0,debit card,NaN,NaN

In [96]:
o_df["net_quantity"]=o_df["net_quantity"].astype(int)

In [97]:
o_df.head()

,order_id,customer_id,product_id,order_date,net_quantity,payment_mode,total_amount,amount_saved
0,O5000,C415,P1076,2025-01-06,4,credit card,NaN,NaN
1,O5001,C534,P1012,2025-09-03,5,cash,NaN,NaN
2,O5002,C291,P1069,2025-04-09,4,credit card,NaN,NaN
3,O5003,C650,P1090,2023-05-21,5,cash,NaN,NaN
4,O5004,C856,P1019,2023-07-05,5,debit card,NaN,NaN

In [98]:
o_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      500 non-null    str
 1   customer_id   500 non-null    str
 2   product_id    500 non-null    str
 3   order_date    500 non-null    datetime64[us]
 4   net_quantity  500 non-null    int64
 5   payment_mode  500 non-null    str
 6   total_amount  0 non-null      float64
 7   amount_saved  0 non-null      float64
dtypes: datetime64[us](1), float64(2), int64(1), str(4)
memory usage: 31.4 KB

In [99]:
# o_df=o_df.merge(p_df[["price","discounted amount","product_id"]],on="product_id", how="inner")
o_df=pd.merge(o_df,p_df[['product_id','discounted amount','price']],on='product_id',how='inner')

In [100]:
# o_df=o_df.merge(p_df[["price","discounted amount","product_id"]],on="product_id", how="inner")
# o_dfo_df['total_amount']=o_df['discounted amount']*o_df['net_quantity']
# o_df['price']= o_df['price']*o_df['net_quantity']
# o_df['amount_saved']=o_df["price"] - o_df["total_amount"]

In [101]:
o_df['actual_total']=o_df['price']*o_df['net_quantity']
o_df['amount_to_be_paid']=o_df['discounted amount'] * o_df['net_quantity']
o_df['amount_saved']=o_df['actual_total']- o_df['amount_to_be_paid']

o_df=o_df.drop(columns=['price','discounted amount','total_amount'])

In [102]:
o_df

,order_id,customer_id,product_id,order_date,net_quantity,payment_mode,amount_saved,actual_total,amount_to_be_paid
0,O5000,C415,P1076,2025-01-06,4,credit card,720.00,4800,4080.00
1,O5001,C534,P1012,2025-09-03,5,cash,1012.50,6750,5737.50
2,O5002,C291,P1069,2025-04-09,4,credit card,0.00,400,400.00
3,O5003,C650,P1090,2023-05-21,5,cash,5000.00,6750,1750.00
4,O5004,C856,P1019,2023-07-05,5,debit card,0.00,6750,6750.00
...,...,...,...,...,...,...,...,...,...
487,O5495,C993,P1024,2023-08-06,5,credit card,600.00,6000,5400.00
488,O5496,C970,P1087,2023-07-13,3,credit card,236.25,1575,1338.75
489,O5497,C657,P1036,2023-07-23,5,debit card,5000.00,5590,590.00
490,O5498,C257,P1022,2024-10-30,2,credit card,30.00,200,170.00
491,O5499,C559,P1078,2023-08-05,4,credit card,4000.00,2100,-1900.00

In [103]:
o_df['payment_mode'].unique()

<StringArray>
['credit card', 'cash', 'debit card', 'net banking', 'upi']
Length: 5, dtype: str

*Exporting the data*

In [104]:
c_df.to_csv('cleaned_datasets/customer.csv' ,index=False)

In [105]:
p_df.to_json('cleaned_datasets/product.json', index=False,indent=True)

C:\Users\ANJANA\AppData\Local\Temp\ipykernel_1988\2832114041.py:1: Pandas4Warning: The default 'epoch' date format is deprecated and will be removed in a future version, please use 'iso' date format instead.
  p_df.to_json('cleaned_datasets/product.json', index=False,indent=True)

In [106]:
o_df.to_excel('cleaned_datasets/orders.xlsx', index=False)